import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1512,height:1120}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));const base='http://127.0.0.1:5173';
await page.goto(base);await page.getByText('WS LIVE',{exact:true}).waitFor();
await page.getByRole('button',{name:'Navigation',exact:true}).click();await page.getByText('One platform. A global perspective.').waitFor();await page.waitForTimeout(2500);
await page.screenshot({path:'/home/user/navigation-day.png',fullPage:true});
const data=await (await page.request.get(base+'/api/latest')).json();console.log('Coordinate source:',data.source,data.navigation.latitude,data.navigation.longitude);
for(const theme of ['Dark ocean','Night watch','Day']){await page.getByRole('button',{name:theme+' theme',exact:true}).click();await expect(page.getByRole('button',{name:theme+' theme',exact:true})).toHaveAttribute('aria-pressed','true');if(theme!=='Day')await page.screenshot({path:'/home/user/navigation-'+theme.split(' ')[0].toLowerCase()+'.png',fullPage:true});}
await page.getByLabel('Clock timezone').selectOption('Asia/Kolkata');await page.reload();await expect(page.getByLabel('Clock timezone')).toHaveValue('Asia/Kolkata');console.log('Theme and timezone persistence passed');
await page.getByRole('button',{name:'Ocean Reports',exact:true}).click();await page.getByRole('button',{name:'Generate preview',exact:true}).waitFor();const before=(await (await page.request.get(base+'/api/reports')).json()).schedule.next_due;
await page.getByRole('button',{name:'Generate preview',exact:true}).click();await page.getByText('PREVIEW · INCOMPLETE REPORTING WINDOW',{exact:true}).waitFor();await expect(page.getByRole('link',{name:'Download CSV'})).toBeVisible();
const list=await(await page.request.get(base+'/api/reports')).json();if(list.schedule.next_due!==before)throw Error('Preview moved schedule');const csv=await(await page.request.get(base+'/api/reports/'+list.reports[0].id+'/download?format=csv')).text();if(!csv.includes('ocean.temperature'))throw Error('Missing CSV metric');await page.screenshot({path:'/home/user/ocean-reports.png',fullPage:true});console.log('Report preview, provenance, CSV and schedule persistence passed');
for(const name of ['Mission Overview','Ocean Observations','Atmosphere','Wave & Motion','Ice Detection','Power & Energy','Communication','Mission Control','System Health','Data Explorer','Software Architecture','Mission Timeline']){await page.getByRole('button',{name,exact:true}).click();await page.waitForTimeout(120);}console.log('All 14 pages opened');
await page.getByRole('button',{name:'Navigation',exact:true}).click();await page.getByTitle('Locate platform from telemetry').click();await page.waitForTimeout(400);await page.getByTitle('Show the whole world').click();await page.getByLabel('Map basemap').selectOption('ocean');await page.waitForTimeout(1200);await page.getByLabel('Map basemap').selectOption('world');
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);await page.screenshot({path:'/home/user/navigation-mobile.png',fullPage:true});let overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);console.log('Mobile horizontal overflow:',overflow);console.log('Page errors:',errors);await browser.close();if(errors.length||overflow)process.exit(1);
