import React,{useEffect,useState} from 'react';
import {ArrowDownToLine,CalendarDays,CheckCheck,ChevronRight,Clock3,FileText,Inbox,RefreshCw,Send,Waves} from 'lucide-react';
interface ReportSummary{id:number;kind:string;period_start:string;period_end:string;generated_at:string;unread:boolean;sample_count:number;sources:Record<string,number>}
interface Report extends ReportSummary{title:string;window_days:number;delivery:string;coverage_percent:number;expected_samples_at_7s:number;samples_with_unavailable_channels:number;summary:string[];disclaimer:string;ice_risk_counts:Record<string,number>;states:Record<string,number>;metrics:Record<string,{label:string;unit:string;min:number|null;max:number|null;mean:number|null;valid_samples:number;latest:number|null}>}
interface Schedule{interval_days:number;next_due:string;anchor:string;destination:string;unread:number;total:number}
const date=(s:string)=>new Date(s).toLocaleString('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})+' UTC';
const f=(n:number|null)=>n==null?'—':n.toFixed(2);
export function OceanReports({clock}:{clock:number}){
 const [rows,setRows]=useState<ReportSummary[]>([]),[schedule,setSchedule]=useState<Schedule|null>(null),[report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){try{const r=await fetch('/api/reports');if(!r.ok)throw Error('Report inbox unavailable');const b=await r.json();setRows(b.reports);setSchedule(b.schedule)}catch(e){setError(String(e))}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,10000);return()=>clearInterval(timer)},[]);
 async function open(id:number){setBusy(true);try{const r=await fetch('/api/reports/'+id);if(!r.ok)throw Error('Unable to open report');setReport(await r.json());await fetch(`/api/reports/${id}/read`,{method:'POST'});await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function preview(){setBusy(true);setError('');try{const r=await fetch('/api/reports/preview',{method:'POST'});if(!r.ok)throw Error('Unable to generate report');setReport(await r.json());await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 const remaining=schedule?Math.max(0,Date.parse(schedule.next_due)-clock):0;const days=Math.floor(remaining/86400000),hours=Math.floor(remaining/3600000)%24;
 return <><div className="report-hero"><div className="report-hero-icon"><Waves size={32}/></div><div><span className="eyebrow">AUTOMATED MARINE OBSERVATION BULLETIN</span><h2>Ocean intelligence, every ten days.</h2><p>A factual digest of recorded conditions, delivered to your mission inbox. No invented observations, forecasts or external email delivery.</p></div><button className="primary" disabled={busy} onClick={preview}><FileText size={15}/>{busy?'Preparing…':'Generate preview'}</button></div>
 {error&&<div className="notice amber-notice">{error}</div>}
 <div className="report-schedule"><div><CalendarDays size={20}/><span>REPORTING INTERVAL<strong>10 days <small>240 hours · UTC</small></strong></span></div><div><Clock3 size={20}/><span>NEXT DELIVERY<strong>{schedule?date(schedule.next_due):'Loading schedule…'}</strong></span></div><div><Send size={20}/><span>DELIVERY DESTINATION<strong>Dashboard inbox</strong></span></div><div><Inbox size={20}/><span>COUNTDOWN<strong>{days}d {hours}h <small>remaining</small></strong></span></div></div>
 <div className="report-layout"><section className="panel report-inbox"><div className="panel-head"><h3>Bulletin inbox <span className="inbox-count">{rows.length}</span></h3><button className="icon-button" aria-label="Refresh reports" onClick={refresh}><RefreshCw size={14}/></button></div>{rows.length?rows.map(r=><button key={r.id} className={'report-row '+(report?.id===r.id?'selected-report':'')} onClick={()=>open(r.id)}><span className="report-file"><FileText size={20}/></span><span><b>Ocean conditions <small>#{String(r.id).padStart(3,'0')}</small></b><em>{r.kind==='PREVIEW'?'Partial-window preview':'Scheduled 10-day bulletin'}</em><small>{date(r.generated_at)}</small><span className="report-row-tags"><i>{r.sample_count.toLocaleString()} samples</i><i>{Object.keys(r.sources).join(' / ')||'NO DATA'}</i></span></span>{r.unread&&<span className="unread-dot"/>}<ChevronRight size={15}/></button>):<div className="report-empty-list"><Inbox size={28}/><h3>Your first bulletin is on its way</h3><p>It will appear here automatically after the first 10-day reporting window. Generate a labeled preview to inspect data collected so far.</p></div>}<div className="report-note"><CheckCheck size={14}/><p>Schedule and reports are saved in SQLite. Restarting the backend does not reset the next delivery. Missed windows are processed on restart.</p></div></section>
 <section className="panel report-document">{report?<><div className="bulletin-masthead"><span>NEELA YAAN / MARINE OBSERVATIONS</span><b>NY–01</b></div><div className="bulletin-title"><div className="eyebrow">{report.kind==='PREVIEW'?'PREVIEW · INCOMPLETE REPORTING WINDOW':'SCHEDULED · 10-DAY REPORT'}</div><h2>{report.title}</h2><p>{date(report.period_start)} — {date(report.period_end)}</p><span className="bulletin-source">{Object.keys(report.sources).join(' / ')||'NO DATA'} · {report.delivery}</span></div><div className="bulletin-stats"><div><b>{report.sample_count.toLocaleString()}</b><span>recorded samples</span></div><div><b>{report.window_days}</b><span>days covered</span></div><div><b>{report.samples_with_unavailable_channels}</b><span>samples with unavailable channels</span></div></div><div className="bulletin-summary"><h3>Conditions summary</h3>{report.summary.map((s,i)=><p key={i}>{s}</p>)}</div><div className="bulletin-table-wrap"><table><thead><tr><th>PARAMETER</th><th>MINIMUM</th><th>AVERAGE</th><th>MAXIMUM</th><th>UNIT</th></tr></thead><tbody>{Object.entries(report.metrics).map(([p,m])=><tr key={p}><td>{m.label}</td><td>{f(m.min)}</td><td>{f(m.mean)}</td><td>{f(m.max)}</td><td>{m.unit}</td></tr>)}</tbody></table></div><p className="panel-note">{report.disclaimer}</p><div className="bulletin-downloads"><a className="button" href={`/api/reports/${report.id}/download?format=csv`}><ArrowDownToLine size={14}/> Download CSV</a><a className="button" href={`/api/reports/${report.id}/download?format=json`}><ArrowDownToLine size={14}/> Download full JSON</a></div></>:<div className="report-empty"><div className="report-empty-mark"><Waves size={42}/></div><span className="eyebrow">A CLEARER PICTURE OF THE OCEAN</span><h2>Your observation record,<br/>beautifully summarized.</h2><p>Select a bulletin from the inbox, or generate a preview from the data already recorded. Scheduled reports continue every ten days without resetting the cadence.</p><div className="report-empty-pills"><span>Ocean & atmosphere</span><span>Ice & mission states</span><span>Power & quality</span></div></div>}</section></div>
 <div className="notice"><CalendarDays size={16}/> Automatic delivery runs while the backend is online and catches up after downtime. Reports contain recorded data only; outages are not filled with simulated historical readings. A preview never resets the 10-day schedule.</div></>
}
